#!/bin/bash

protected_branch='refs/heads/master'

remote=$2
protected_service=*github*

while read local_ref local_sha remote_ref remote_sha
do
  if [[ $local_ref = $protected_branch ]]  && [[ $remote == $protected_service ]]
  then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
      exit 0 # push will execute
    fi
    exit 1 # push will not execute
  else
    exit 0 # push will execute
  fi
done
