#!/bin/bash

protected_branches=(master main)

remote=$2
protected_service=*github*

if [[ $remote != $protected_service ]]; then
  exit 0
fi

while read local_ref local_sha remote_ref remote_sha; do
  for i in "${protected_branches[@]}"; do
    if [ "refs/heads/$i" == $local_ref ]; then
      read -p "You're about to push the $i branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
      echo
      if echo $REPLY | grep -E '^[Yy]$' > /dev/null
      then
        exit 0 # push will execute
      fi
      exit 1 # push will not execute
    fi
  done
done
