#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"
PRIVATE_ROOT="$DOTFILES_ROOT/private/"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your git name?'
    read -e git_authorname
    user ' - What is your git work email?'
    read -e git_authorworkemail
    user ' - What is your git home email?'
    read -e git_authorhomeemail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHORWORKEMAIL/$git_authorworkemail/g" -e "s/AUTHORHOMEEMAIL/$git_authorhomeemail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

setup_gemrc () {
  if ! [ -f ruby/gemrc.symlink ]
  then
    info 'setup gemrc'

    cp ruby/gemrc.symlink.example ruby/gemrc.symlink

    success 'gemrc'
  fi
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT $PRIVATE_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done
}

brew_install() {
  brew list $1 &>/dev/null || brew install $1
}

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  info "installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

setup_gitconfig
setup_gemrc
install_dotfiles

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  # Set OS X defaults
  ./osx/set-defaults.sh
  # Upgrade homebrew
  brew update
  # Install homebrew packages
  brew_install tmux
  brew_install vim
  brew_install michaeldfallen/formula/git-radar
  brew_install rbenv
  brew_install reattach-to-user-namespace
  brew_install git-secrets
  brew_install go
  brew_install golangci/tap/golangci-lint
  brew_install nvm
  brew_install direnv
  brew_install languagetool
  brew_install rust-analyzer
fi

info "installing go dependencies"
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/lint/golint@latest

info "installing vim dependencies"
./vim/install.sh

info "installing submodules"
git submodule sync
git submodule update --init

echo ''
echo '  All installed!'
